version: '3.9'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: Howmanyteascanyoureat
      MYSQL_DATABASE: demo
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net
    

  backend:
    build:
      context: ./vargo
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Howmanyteascanyoureat
    networks:
      - app-net

  frontend:
    build:
      context: ./ui
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
